version: '3'

services:

  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:80"
    expose:
      - "8080"

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "D3vP@ss!8"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - ./.volumes/sqlserver/data:/var/opt/mssql/data
      - ./.volumes/sqlserver/log:/var/opt/mssql/log
      - ./.volumes/sqlserver/secrets:/var/opt/mssql/secrets
    networks:
      - app-network
    ports:
      - "1433:1433"

networks:
  app-network:
    name: app-network
    driver: bridge