version: '3'

services:

  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api-network
    ports:
      - "8080:80"
    expose:
      - "8080"

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      SA_PASSWORD: "D3vP@ss!8"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - db-data:/var/opt/mssql/data
      - db-log:/var/opt/mssql/log
      - db-secrets:/var/opt/mssql/secrets
    networks:
      - api-network
    ports:
      - "1433:1433"

volumes:

  db-data:
    name: db-data
    driver: local

  db-log:
    name: db-log
    driver: local

  db-secrets:
    name: db-secrets
    driver: local

networks:

  api-network:
    name: api-network
    driver: bridge